- name: create folder jenkins
  community.general.jenkins_job_info:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: CI Pipeline
    password: "{{jenkins-password}}"
    url: http://172.31.14.228:8080
    user: admin
- name: create pipeline
  community.general.jenkins_job_info:
    config: "{{ lookup('file', 'templates/job.xml') }}"
    name: "{ { component } }"
    password: "{{jenkins-password}}"
    url: http://172.31.14.228:8080
    user: admin


